### ISSUE TITLE
specialops crash when the bitcore-node startup

### ISSUE THREAD

**Issue by qinfengling** [poexio/specialops#16]
__Call stack__

[2018-04-02T12:21:06.225Z] warn: Reorg detected! Current tip: 0000000000000000000000000000000000000000000000000000000000000000
[2018-04-02T12:21:06.225Z] info: disconnecting block undefined undefined
[2018-04-02T12:21:06.227Z] warn: Disconnected current tip. New tip is 0000000000000000000000000000000000000000000000000000000000000000
[2018-04-02T12:21:06.240Z] error: uncaught exception: TypeError: Cannot read property 'rhash' of undefined
    at /home/node/fullnode/bitcore/node_modules/specialops/lib/index.js:197:21
    at /home/node/fullnode/bitcore/node_modules/bitcore-node/lib/services/block/index.js:471:14
    at /home/node/fullnode/bitcore/node_modules/bitcore-node/lib/services/db/index.js:107:16
    at /home/node/fullnode/bitcore/node_modules/levelup/lib/levelup.js:168:14
[2018-04-02T12:21:06.241Z] error: TypeError: Cannot read property 'rhash' of undefined
    at /home/node/fullnode/bitcore/node_modules/specialops/lib/index.js:197:21
    at /home/node/fullnode/bitcore/node_modules/bitcore-node/lib/services/block/index.js:471:14
    at /home/node/fullnode/bitcore/node_modules/bitcore-node/lib/services/db/index.js:107:16
    at /home/node/fullnode/bitcore/node_modules/levelup/lib/levelup.js:168:14

**Comment by qinfengling** [comment]
Fixed in 8c4fe67b0f4c575592640e7ad0674b58c2b0a3ae

The crash caused by invalid hash, when the block height is 0, the block hash is not assigned any value. so the reorg will fail.
