### ISSUE TITLE
can't start the specialops service

### ISSUE THREAD

**Issue by qinfengling** [poexio/specialops#20]
When start the specialops service, it crash with the call stack like this:

```
[2018-05-14T08:26:09.750Z] error: uncaught exception: Error: Callback was already called.
    at /home/node/fullnode/bitcore/node_modules/async/dist/async.js:955:32
    at /home/node/fullnode/bitcore/node_modules/bitcore-node/lib/node.js:140:14
    at /home/node/fullnode/bitcore/node_modules/specialops/lib/index.js:443:16
    at /home/node/fullnode/bitcore/node_modules/specialops/lib/index.js:55:16
    at /home/node/fullnode/bitcore/node_modules/bitcore-node/lib/services/header/index.js:617:14
    at /home/node/fullnode/bitcore/node_modules/bitcore-node/lib/services/db/index.js:107:16
    at /home/node/fullnode/bitcore/node_modules/levelup/lib/levelup.js:168:14
[2018-05-14T08:26:09.751Z] info: Beginning shutdown
[2018-05-14T08:26:09.751Z] warn: Node is stopping, gently closing the database. Please wait, this could take a while.
```

**Comment by qinfengling** [comment]
It happens when the tipData was correct, but the block data was corrupt in the Bitcore Node, need to rewind the new and correct tipData.
